import { Product, Testimonial, Benefit } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Legging Premium Black',
    category: 'leggings',
    price: 189.90,
    originalPrice: 249.90,
    image: '/images/produtos/1.png',
    description: 'Legging em nylon premium com cintura alta e suporte total. Perfeita para treinos intensos.',
    colors: ['preto', 'rosa-blush'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    isNew: false,
    isBestseller: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: '2',
    name: 'Legging Blush Comfort',
    category: 'leggings',
    price: 179.90,
    image: '/images/produtos/2.png',
    description: 'Legging em tom blush com tecnologia anti-transparência. Ultra confortável o dia todo.',
    colors: ['rosa-blush', 'rosa-claro', 'off-white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isNew: true,
    rating: 4.9,
    reviews: 87,
  },
  {
    id: '3',
    name: 'Top Fitness Rose Light',
    category: 'tops',
    price: 129.90,
    originalPrice: 159.90,
    image: '/images/produtos/3.png',
    description: 'Top fitness em rosa claro com suporte integrado. Ideal para pilates e yoga.',
    colors: ['rosa-claro', 'preto'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isBestseller: true,
    rating: 4.7,
    reviews: 95,
  },
  {
    id: '4',
    name: 'Top Cross Black',
    category: 'tops',
    price: 139.90,
    image: '/images/produtos/4.png',
    description: 'Top cruzado preto com costas abertas. Estilo que não compromete o conforto.',
    colors: ['preto', 'rosa-blush'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    isNew: false,
    rating: 4.6,
    reviews: 72,
  },
  {
    id: '5',
    name: 'Conjunto Two-Piece Rose',
    category: 'conjuntos',
    price: 299.90,
    originalPrice: 349.90,
    image: '/images/produtos/5.png',
    description: 'Conjunto elegante com top e bicicleta em tom rosa. Perfeito para treinos e lifestyle.',
    colors: ['rosa-claro', 'rosa-blush'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isBestseller: true,
    rating: 4.9,
    reviews: 156,
  },
  {
    id: '6',
    name: 'Conjunto Black Minimal',
    category: 'conjuntos',
    price: 319.90,
    image: '/images/produtos/6.png',
    description: 'Conjunto minimalista em preto com detalhes em off-white. Elegância em movimento.',
    colors: ['preto', 'off-white'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isNew: true,
    rating: 4.8,
    reviews: 103,
  },
  {
    id: '7',
    name: 'Macaquinho Premium',
    category: 'macaquinhos',
    price: 249.90,
    image: '/images/produtos/7.png',
    description: 'Macaquinho em nylon premium com alças ajustáveis. Uma peça, múltiplas possibilidades.',
    colors: ['preto', 'rosa-blush'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    rating: 4.7,
    reviews: 68,
  },
  {
    id: '8',
    name: 'Macaquinho Rose Elegant',
    category: 'macaquinhos',
    price: 269.90,
    originalPrice: 319.90,
    image: '/images/produtos/8.png',
    description: 'Macaquinho em rosa claro com costas abertas. Sofisticação em cada movimento.',
    colors: ['rosa-claro', 'rosa-blush'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    isBestseller: true,
    rating: 4.9,
    reviews: 112,
  },
  {
    id: '9',
    name: 'Fone de Ouvido Wireless Rose',
    category: 'acessorios',
    price: 199.90,
    image: '/images/produtos/9.png',
    description: 'Fone wireless com som premium e bateria de 24h. Companheiro perfeito de treinos.',
    colors: ['rosa-blush'],
    sizes: ['S'],
    isNew: true,
    rating: 4.8,
    reviews: 45,
  },
  {
    id: '10',
    name: 'Mochila Fitness Black',
    category: 'acessorios',
    price: 229.90,
    originalPrice: 279.90,
    image: '/images/produtos/10.png',
    description: 'Mochila resistente com compartimentos inteligentes. Para quem se move com estilo.',
    colors: ['preto', 'rosa-blush'],
    sizes: ['S'],
    rating: 4.7,
    reviews: 81,
  },
  {
    id: '11',
    name: 'Garrafa Térmica Rose',
    category: 'acessorios',
    price: 89.90,
    image: '/images/produtos/11.png',
    description: 'Garrafa térmica 500ml mantém bebida quente ou fria por 12h. Design minimalista.',
    colors: ['rosa-claro', 'rosa-blush', 'preto'],
    sizes: ['S'],
    isBestseller: true,
    rating: 4.6,
    reviews: 134,
  },
  {
    id: '12',
    name: 'Meias Premium Cotton',
    category: 'acessorios',
    price: 39.90,
    originalPrice: 49.90,
    image: '/images/produtos/12.png',
    description: 'Meias em algodão premium com amortecimento. Conforto do primeiro ao último passo.',
    colors: ['preto', 'rosa-blush', 'off-white'],
    sizes: ['S'],
    isNew: false,
    rating: 4.5,
    reviews: 203,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Marina S.',
    text: 'Transformou minha rotina de treinos. O conforto e o estilo que eu procurava finalmente encontrei!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Ana P.',
    text: 'Qualidade impecável. Uso diariamente e não consigo mais treinar com outra marca.',
    rating: 5,
  },
  {
    id: '3',
    name: 'Sofia L.',
    text: 'Estou completamente apaixonada! Cada peça é um investimento em confiança e estilo.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Gabriela M.',
    text: 'FOCO Woman entendeu exatamente o que uma mulher quer. Perfeito!',
    rating: 5,
  },
];

export const BENEFITS: Benefit[] = [
  {
    id: '1',
    title: 'Conforto total',
    description: 'Tecidos com toque macio e respirabilidade, pensados para longas sessões na academia.',
    iconId: 'comfort',
  },
  {
    id: '2',
    title: 'Estilo impecável',
    description: 'Silhuetas limpas e acabamento cuidadoso — do treino ao pós-treino, sem excesso de informação.',
    iconId: 'style',
  },
  {
    id: '3',
    title: 'Performance',
    description: 'Compressão e elasticidade equilibradas para suportar agachamento, corrida e mobilidade.',
    iconId: 'performance',
  },
  {
    id: '4',
    title: 'Caimento preciso',
    description: 'Modelagem que acompanha curvas reais, com proporções testadas em movimento.',
    iconId: 'fit',
  },
];

export const CATEGORIES = [
  { id: 'leggings', name: 'Leggings', count: 0 },
  { id: 'tops', name: 'Tops', count: 0 },
  { id: 'conjuntos', name: 'Conjuntos', count: 0 },
  { id: 'macaquinhos', name: 'Macaquinhos', count: 0 },
  { id: 'acessorios', name: 'Acessórios', count: 0 },
];

// Count products per category
CATEGORIES.forEach(cat => {
  cat.count = PRODUCTS.filter(p => p.category === cat.id).length;
});
